name: Claude Code Review

on:
  # Automatic review on PR events
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches: [ main ]
    paths: 
      - 'weeks/**'
      - 'projects/**'
  # Manual trigger with @claude mentions
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.draft == false) ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Enable automatic review mode for PR events
          direct_prompt: |
            ${{ github.event_name == 'pull_request' && 
            'Please provide an automatic code review with inline comments for this PR. Focus on:
            - Code quality and best practices
            - Accessibility compliance (WCAG 2.2 AA)
            - Performance considerations
            - Security issues
            - Testing coverage
            - Professional development standards
            
            Provide specific, actionable inline comments on the changed code.' || 
            '' }}

          # Allow Claude to read CI results and run basic commands
          additional_permissions: |
            actions: read
          
          # Enable tools for testing and linting
          allowed_tools: "Bash(npm install),Bash(npm run build),Bash(npm run test),Bash(npm run lint),Bash(npm run typecheck)"
          
          # Use sticky comments for automatic reviews
          use_sticky_comment: true
          
          # Custom instructions for Frontend Mastery Journey project
          custom_instructions: |
            You are reviewing submissions for a 6-month frontend mastery journey targeting junior developer roles in Australia.
            
            Focus on:
            - Weekly learning objectives completion
            - WCAG 2.2 AA accessibility compliance (Lighthouse ≥90)
            - Professional code quality and best practices
            - Git workflow and commit message quality
            - Documentation and case study development
            - Progress tracking validation
            
            For week completion reviews, verify:
            - All TODO comments resolved with proper implementations
            - Projects deployed to public URLs
            - PROGRESS.md and learning logs updated
            - Accessibility requirements met
            - Professional development practices followed
            
            Provide specific, actionable feedback aligned with Australian job market expectations.
          
          # Optional: Custom environment variables for Claude
          # claude_env: |
          #   NODE_ENV: test

